const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const path = require('node:path');
const fs = require('node:fs');
const { chromium, expect: baseExpect } = require('../../frontend/node_modules/@playwright/test');
const expect = baseExpect.configure({ timeout: 60000 });
process.env.JWT_SECRET = 'browser-tests-only-secret';
process.env.NODE_ENV = 'test';
process.env.CLIENT_URL = 'http://localhost:5001';
require.cache[require.resolve('../src/utils/sendEmail')] = { exports: async () => ({ delivered: true, providerMessageId: 'browser-email-id' }) };
require.cache[require.resolve('../src/utils/sendWhatsApp')] = { exports: async () => ({ delivered: true, providerMessageId: 'browser-whatsapp-id' }) };
const app = require('../src/app');
const models = require('../src/config/resources');
const dbName = 'crm_browser_' + Date.now();
let server, browser;
const uploadedFiles=[];
async function main() {
 const frontendDist=path.resolve(__dirname,'../../frontend/dist/index.html');
 assert.ok(fs.existsSync(frontendDist),'Build the frontend before running browser tests.');
 await mongoose.connect('mongodb://127.0.0.1:27017/' + dbName);
 for(const [resource, Model] of Object.entries(models)) {
   if(['roles','users'].includes(resource)) continue;
   const file=path.join(__dirname,'../seed-data',resource+'.json');
   if(fs.existsSync(file)) await Model.insertMany(JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''),(key,value)=>value&&value.$date?new Date(value.$date):value));
 }
 await models.roles.create({name:'viewer',description:'Browser permission test',permissions:['dashboard:read','properties:read','menu:dashboard','menu:properties','menu:profile']});
 await models.users.create({name:'Browser Admin',email:'browser@test.local',password:'BrowserPassword123!',role:'admin',isEmailVerified:true});
 await models.users.create({name:'Browser Viewer',email:'viewer@test.local',password:'ViewerPassword123!',role:'viewer',isEmailVerified:true});
 await models.users.create({name:'Browser Customer',email:'customer.browser@test.local',password:'CustomerPassword123!',role:'customer',isEmailVerified:true});
 await models.users.create({name:'Browser Staff',email:'staff.browser@test.local',password:'StaffPassword123!',role:'staff',isEmailVerified:true});
 const visitAgent=await models.agents.findOne();const visitProperty=await models.properties.findOne();
 assert.ok(visitAgent&&visitProperty,'Browser seed needs an agent and property.');
 await models.properties.findByIdAndUpdate(visitProperty.id,{agentRef:visitAgent.id,agent:visitAgent.name,ownerName:'Browser Property Owner',ownerEmail:'browser.owner@test.local',ownerWhatsapp:'+15550003101'});
 server=app.listen(5001); await new Promise(resolve=>server.once('listening',resolve));
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 page.setDefaultTimeout(60000);
 const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER PAGE ERROR: '+e.message);});
 page.on('console',message=>{if(message.type()==='error')console.error('BROWSER CONSOLE ERROR: '+message.text());});
 page.on('response',response=>{if(response.status()>=400)console.error('BROWSER HTTP ERROR: '+response.status()+' '+response.url());});
 await page.goto('http://localhost:5001/login');
 await page.locator('#email').fill('browser@test.local');
 await page.locator('#login-password').fill('BrowserPassword123!');
 await page.locator('button[type=submit]').click();
 await page.waitForURL('**/index'); await expect(page.getByText('Total Revenue (Won Deals)',{exact:true})).toBeVisible();
 await expect(page.locator('.dashboard-chart canvas')).toHaveCount(4);
 const dashboardArtifacts=path.resolve(__dirname,'../../artifacts');fs.mkdirSync(dashboardArtifacts,{recursive:true});
 await page.waitForTimeout(900);await page.screenshot({path:path.join(dashboardArtifacts,'dashboard-enterprise-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(dashboardArtifacts,'dashboard-enterprise-mobile.png'),fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Dashboard mobile viewport has horizontal overflow');
 await page.setViewportSize({width:1440,height:1050});
 console.log('PASS browser login and live dashboard');
 const routes=['properties','properties/property-grid','properties/property-list','properties/property-map','categories','amenities','manual-tour','agents','customers','leads','deals','appointments','reviews','invoices','payments','transactions','reimbursements','reimbursements/allowances','reimbursements/expenses','reimbursements/travel','reimbursements/meals','reimbursement-types','reports','staff','roles','users','notification-status','settings','profile'];
 for(const route of process.env.SKIP_ROUTE_AUDIT ? [] : routes) {
  await page.goto('http://localhost:5001/'+route);
  await expect(page.locator('h1').first()).toBeVisible();
  await page.waitForTimeout(450);
  assert.ok(!await page.getByRole('alert').count(),'Error state on '+route+': '+await page.locator('[role=alert]').allTextContents());
  console.log('PASS route '+route);
 }
 if(process.env.ROUTES_ONLY)return;

 await page.goto('http://localhost:5001/reimbursements');await expect(page.getByText('Total claims',{exact:true})).toBeVisible();
 await page.locator('.record-workspace > .workspace-heading .ws-button.primary').click();
 await page.getByLabel('Claim Number',{exact:true}).fill('E2E-RMB-001');
 await page.getByLabel('Employee Name *',{exact:true}).fill('Browser Staff');
 await page.getByLabel('Employee Email',{exact:true}).fill('staff.browser@test.local');
 await page.locator('dialog label').filter({hasText:'Kind'}).locator('select').selectOption('Expense');
 await page.locator('dialog label').filter({hasText:'Category'}).locator('select').selectOption('Travel');
 await page.getByLabel('Description *',{exact:true}).fill('Browser reimbursement workflow');
 await page.getByLabel('Amount *',{exact:true}).fill('425.50');
 await page.getByLabel('Expense Date *',{exact:true}).fill('2030-01-10');
 await page.locator('dialog label').filter({hasText:'Status'}).locator('select').selectOption('Submitted');
 await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record saved successfully.');
 await page.getByLabel('Search records').fill('E2E-RMB-001');const reimbursementRow=page.locator('tr').filter({hasText:'E2E-RMB-001'});await expect(reimbursementRow).toBeVisible();
 await reimbursementRow.getByRole('button',{name:'Edit record',exact:true}).click();await page.locator('dialog label').filter({hasText:'Status'}).locator('select').selectOption('Paid');await page.getByLabel('Payment Reference',{exact:true}).fill('PAY-E2E-RMB-001');await page.getByRole('button',{name:'Save record',exact:true}).click();
 await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record saved successfully.');await reimbursementRow.getByRole('button',{name:'Delete record',exact:true}).click();await page.getByRole('button',{name:'Delete record',exact:true}).last().click();await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record deleted.');
 console.log('PASS reimbursement create, summary refresh, edit, filter, and delete');

 const customerPage=await browser.newPage({viewport:{width:1280,height:950}});customerPage.setDefaultTimeout(60000);
 await customerPage.goto('http://localhost:5001/login');await customerPage.locator('#email').fill('customer.browser@test.local');await customerPage.locator('#login-password').fill('CustomerPassword123!');await customerPage.locator('button[type=submit]').click();await customerPage.waitForURL('**/index');
 await customerPage.goto('http://localhost:5001/properties/property-details/'+visitProperty.id);await expect(customerPage.getByText('Schedule a Visit',{exact:true})).toBeVisible();
 await customerPage.locator('#date').fill('20 Sep 2030');await customerPage.locator('#visit-time').fill('11:30');await customerPage.locator('#visit-whatsapp').fill('+1 555 000 3102');await customerPage.locator('#message').fill('Please confirm the parking entrance.');
 await customerPage.locator('button[type="submit"]').filter({hasText:'Request Visit'}).click();await expect(customerPage.getByText('The owner and listing agent were notified.',{exact:true})).toBeVisible();await customerPage.close();
 await page.goto('http://localhost:5001/notification-status');await expect(page.getByText(visitProperty.name,{exact:true}).first()).toBeVisible();await expect(page.getByText('Delivered',{exact:true}).first()).toBeVisible();
 console.log('PASS customer visit booking, automatic email/WhatsApp dispatch, and admin delivery status');
 if(process.env.BOOKING_ONLY)return;

 await page.goto('http://localhost:5001/roles');
 const viewerRoleRow=page.locator('.workspace-table tbody tr').filter({has:page.getByRole('button',{name:'viewer',exact:true})});
 await expect(viewerRoleRow).toBeVisible();
 await viewerRoleRow.getByRole('button',{name:'Edit record',exact:true}).click();
 await expect(page.getByText('Sidebar access',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Reimbursements',{exact:true})).not.toBeChecked();
 await expect(page.getByLabel('Reimbursements / read',{exact:true})).not.toBeChecked();
 await expect(page.getByLabel('Properties',{exact:true})).toBeChecked();
 await page.getByLabel('Properties',{exact:true}).uncheck();
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record saved successfully.');

 const viewerPage=await browser.newPage({viewport:{width:1280,height:900}});viewerPage.setDefaultTimeout(60000);
 await viewerPage.goto('http://localhost:5001/login');
 await viewerPage.locator('#email').fill('viewer@test.local');await viewerPage.locator('#login-password').fill('ViewerPassword123!');await viewerPage.locator('button[type=submit]').click();
 await viewerPage.waitForURL('**/index');
 await expect(viewerPage.locator('#sidebar').getByText('Dashboard',{exact:true})).toBeVisible();
 await expect(viewerPage.locator('#sidebar').getByText('Properties',{exact:true})).toHaveCount(0);
 await expect(viewerPage.locator('#sidebar').getByText('Payments',{exact:true})).toHaveCount(0);
 await viewerPage.goto('http://localhost:5001/properties');await expect(viewerPage.getByText('Access denied',{exact:true})).toBeVisible();
 await viewerPage.getByRole('button',{name:'Assistant chat',exact:true}).click();
 await viewerPage.getByLabel('Message',{exact:true}).fill('I want to schedule a tour');await viewerPage.getByRole('button',{name:'Send message',exact:true}).click();
 await expect(viewerPage.locator('.chat-message').filter({hasText:/Appointments|Manual Tour/}).last()).toBeVisible();
 await viewerPage.close();
 console.log('PASS role checkbox access and Viewer assistant chat');

 const staffPage=await browser.newPage({viewport:{width:1280,height:900}});staffPage.setDefaultTimeout(60000);
 await staffPage.goto('http://localhost:5001/login');await staffPage.locator('#email').fill('staff.browser@test.local');await staffPage.locator('#login-password').fill('StaffPassword123!');await staffPage.locator('button[type=submit]').click();await staffPage.waitForURL('**/index');
 await staffPage.getByRole('button',{name:'Team chat',exact:true}).click();await expect(staffPage.getByText('Browser Admin',{exact:true}).first()).toBeVisible();
 await page.getByRole('button',{name:'Team chat',exact:true}).click();const staffContact=page.locator('.chat-contact').filter({hasText:'Browser Staff'});await expect(staffContact).toBeVisible();if(!(await staffContact.getAttribute('class'))?.includes('active'))await staffContact.click();
 await page.getByLabel('Message',{exact:true}).fill('Browser live hello');await page.getByRole('button',{name:'Send message',exact:true}).click();
 await expect(staffPage.locator('.chat-message').filter({hasText:'Browser live hello'})).toBeVisible();
 await staffPage.getByLabel('Message',{exact:true}).fill('Live reply received');await staffPage.getByRole('button',{name:'Send message',exact:true}).click();
 await expect(page.locator('.chat-message').filter({hasText:'Live reply received'})).toBeVisible();
 await staffPage.close();await page.getByRole('button',{name:'Close chat',exact:true}).click();
 console.log('PASS real-time internal chat in two authenticated sessions');

 await page.goto('http://localhost:5001/properties/add-property');
 const uploadPromise=page.waitForResponse(response=>response.url().endsWith('/api/v1/uploads/images')&&response.request().method()==='POST');
 await page.locator('.image-file-input').first().setInputFiles({name:'browser-property.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});
 const imageResponse=await uploadPromise;assert.equal(imageResponse.status(),201);const imageBody=await imageResponse.json();
 uploadedFiles.push(path.resolve(__dirname,'..',imageBody.data[0].url.replace(/^\//,'')));
 await expect(page.locator('.image-preview-grid img').first()).toBeVisible();
 await page.locator('#name').fill('Browser Image Property');await page.locator('#location').fill('Pune, India');await page.locator('#price').fill('950000');
 await page.locator('form button[type="submit"]').click();await page.waitForURL('**/properties');
 await page.getByPlaceholder('Search properties...').fill('Browser Image Property');await expect(page.getByText('Browser Image Property',{exact:true})).toBeVisible();
 console.log('PASS choose-image upload, preview, save, and property rendering');

 await page.goto('http://localhost:5001/payments');
 await expect(page.locator('h1').filter({hasText:'Payments'})).toBeVisible();
 await expect(page.locator('.record-workspace > .workspace-heading')).toBeVisible();
 const addRecord=page.locator('.record-workspace > .workspace-heading .ws-button.primary');
 await expect(addRecord).toBeVisible();
 await addRecord.click();
 await page.getByLabel('Reference *',{exact:true}).fill('E2E-PAY-001');
 await page.getByLabel('Client *',{exact:true}).fill('Browser Customer');
 await page.getByLabel('Amount *',{exact:true}).fill('1250');
 await page.locator('dialog label').filter({hasText:'Status'}).locator('select').selectOption('Completed');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 const saveOutcome=page.locator('.record-workspace > .ws-notice, dialog .ws-error').first();
 await expect(saveOutcome).toBeVisible();
 if ((await saveOutcome.getAttribute('class'))?.includes('ws-error')) throw new Error('Payment save failed: '+await saveOutcome.innerText());
 await expect(saveOutcome).toContainText('Record saved successfully.');
 await page.reload();
 const row=page.locator('tr').filter({hasText:'E2E-PAY-001'});
 await expect(row).toBeVisible();
 await row.getByRole('button',{name:'Edit record',exact:true}).click();
 await page.getByLabel('Amount *',{exact:true}).fill('2500');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record saved successfully.');
 const exportLink=page.locator('.record-workspace > .workspace-heading a[download]');await expect(exportLink).toBeVisible();
 const download=page.waitForEvent('download');await exportLink.click();assert.ok((await download).suggestedFilename().endsWith('.csv'));
 await row.getByRole('button',{name:'Delete record',exact:true}).click();
 await page.getByRole('button',{name:'Delete record',exact:true}).last().click();
 await expect(page.locator('.record-workspace > .ws-notice')).toContainText('Record deleted.');
 await expect(page.locator('tr').filter({hasText:'E2E-PAY-001'})).toHaveCount(0);
 console.log('PASS payment create, reload, edit, CSV download, delete');
 await page.goto('http://localhost:5001/settings');
 await page.getByLabel('Company name *',{exact:true}).fill('Enterprise Browser Co');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByText('Organization settings saved.',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByLabel('Company name *',{exact:true})).toHaveValue('Enterprise Browser Co');
 await page.getByRole('button',{name:'Audit trail',exact:true}).click();await expect(page.getByText('Enterprise Browser Co',{exact:true})).toBeVisible();
 console.log('PASS settings persistence and audit trail');
 await page.goto('http://localhost:5001/leads');await expect(page.locator('h1').filter({hasText:'Leads'}).first()).toBeVisible();
 const managerButton=page.locator('.workspace-tools > button');await expect(managerButton).toContainText('Manage all records');await managerButton.click();
 await expect(page.locator('.workspace-manager .workspace-actions .ws-button.primary')).toContainText('Add record');
 await page.locator('.workspace-manager').getByLabel('Search records').fill('NONEXISTENT-RECORD');
 await expect(page.getByText('No matching records',{exact:true})).toBeVisible();
 console.log('PASS shared record manager and empty search');
 await page.goto('http://localhost:5001/payments');await page.getByLabel('Search workspace',{exact:true}).fill('Mariana');
 await expect(page.locator('.global-search-results a').first()).toBeVisible();
 await page.locator('.global-search-results a').first().click();await page.waitForURL('**/property-details/**');
 console.log('PASS global search to property details');
 const artifacts=path.resolve(__dirname,'../../artifacts');fs.mkdirSync(artifacts,{recursive:true});
 await page.goto('http://localhost:5001/reports');await page.waitForTimeout(1000);await page.screenshot({path:path.join(artifacts,'reports-desktop.png'),fullPage:true});
 await page.goto('http://localhost:5001/payments');await page.waitForTimeout(700);await page.screenshot({path:path.join(artifacts,'payments-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'payments-mobile.png'),fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile viewport has horizontal overflow');
 assert.deepEqual(errors,[]);
 console.log('PASS desktop/mobile screenshots, no browser exceptions, no mobile overflow');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(async()=>{
 if(browser)await browser.close();
 if(server)await new Promise(resolve=>server.close(resolve));
 for(const file of uploadedFiles)if(file.startsWith(path.resolve(__dirname,'../uploads')+path.sep))try{fs.unlinkSync(file);}catch{}
 if(mongoose.connection.readyState===1&&mongoose.connection.name===dbName&&dbName.startsWith('crm_browser_'))await mongoose.connection.dropDatabase();
 await mongoose.disconnect();
});

