const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const mongoose = require('mongoose');
process.env.JWT_SECRET = 'integration-test-secret-not-used-in-production';
process.env.NODE_ENV = 'test';
process.env.CLIENT_URL = 'http://localhost:5174';
let lastEmail; const sentEmails = []; const sentWhatsapps = [];
require.cache[require.resolve('../src/utils/sendEmail')] = { exports: async message => { lastEmail = message; sentEmails.push(message); return { delivered: true, providerMessageId: 'test-email-id' }; } };
require.cache[require.resolve('../src/utils/sendWhatsApp')] = { exports: async message => { sentWhatsapps.push(message); return { delivered: true, providerMessageId: 'test-whatsapp-id' }; } };
const app = require('../src/app');
const models = require('../src/config/resources');
const User = require('../src/models/User');
const NotificationDelivery = require('../src/models/NotificationDelivery');
const dbName = 'crm_integration_' + Date.now();
let server; let checks = 0; let uploadedFile;
async function main() {
 await mongoose.connect('mongodb://127.0.0.1:27017/' + dbName, { serverSelectionTimeoutMS: 5000 });
 const admin = await User.create({ name:'Test Admin',email:'admin@test.local',password:'TestPassword123!',role:'admin' });
 const agent = await User.create({ name:'Test Agent',email:'agent@test.local',password:'TestPassword123!',role:'agent' });
 const manager = await User.create({ name:'Test Manager',email:'manager@test.local',password:'TestPassword123!',role:'manager' });
 const seniorAgent = await User.create({ name:'Test Senior Agent',email:'senior@test.local',password:'TestPassword123!',role:'senior-agent' });
 const viewer = await User.create({ name:'Test Viewer',email:'viewer@test.local',password:'TestPassword123!',role:'viewer' });
 server = app.listen(0,'127.0.0.1'); await new Promise(resolve=>server.once('listening',resolve));
 const origin='http://127.0.0.1:'+server.address().port;
 const base=origin+'/api/v1';
 let token=admin.getSignedJwtToken();
 const call=async(path,method='GET',body,expected=200,auth=token,extraHeaders={})=>{
  const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{}),...extraHeaders},body:body===undefined?undefined:JSON.stringify(body)});
  const json=await res.json(); assert.equal(res.status,expected,method+' '+path+': '+JSON.stringify(json)); checks++; return json;
 };
 const healthResponse=await fetch(base+'/health');const health=await healthResponse.json();assert.equal(healthResponse.status,200);assert.equal(health.success,true);checks+=2;
 const rootResponse=await fetch(origin+'/');assert.equal(rootResponse.status,200);assert.match(await rootResponse.text(),/Welcome to the API/);checks+=2;
 const preflight=await fetch(base+'/auth/login',{method:'OPTIONS',headers:{Origin:'https://socailsync.com','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),'https://socailsync.com');assert.equal(preflight.headers.get('access-control-allow-credentials'),'true');checks+=3;
 await call('/leads','GET',undefined,401,'');
 const me=await call('/auth/me');assert.equal(me.data.id,String(admin._id));assert.equal(me.data.password,undefined);
 const login=await call('/auth/login','POST',{email:'admin@test.local',password:'TestPassword123!'});assert.ok(login.token);
 for(const internalUser of [admin,manager,seniorAgent,agent])await call('/chat/contacts','GET',undefined,200,internalUser.getSignedJwtToken());
 const fixtures={};
 for(const [resource,Model] of Object.entries(models)){
  if(['roles','users'].includes(resource))continue;
  const body={};
  Model.schema.eachPath((key,path)=>{
   if(['_id','__v','createdAt','updatedAt'].includes(key)||!path.isRequired) return;
   if(path.enumValues?.length)body[key]=path.enumValues[0];
   else if(path.instance==='Number')body[key]=path.options.min||123;
   else if(path.instance==='Date')body[key]='2030-01-10';
   else if(path.instance==='String')body[key]=key.includes('email')?'record@test.local':key==='phone'?'+15550001234':'Test '+resource;
  });
  if(resource==='invoices')body.issueDate='2030-01-01';
  if(resource==='properties')body.type='Villa';
  fixtures[resource]=body;
  const created=await call('/'+resource,'POST',body,201);
  assert.match(created.data.id,/^[a-f0-9]{24}$/);const id=created.data.id;
  const read=await call('/'+resource+'/'+id);assert.equal(read.data.id,id);
  const field=Object.keys(body).find(k=>Model.schema.path(k).instance==='String'&&!Model.schema.path(k).enumValues?.length&&!['email','phone'].includes(k));
  if(field){const update=await call('/'+resource+'/'+id,'PUT',{[field]:'Updated '+resource});assert.equal(update.data[field],'Updated '+resource);}
  await call('/'+resource+'?search=%5B.*&limit=10');
  await call('/'+resource+'/'+id,'DELETE');
  await call('/'+resource+'/'+id,'GET',undefined,404);
  console.log('PASS CRUD '+resource);
 }
 const reimbursementSummary=await call('/reimbursements/summary');assert.equal(reimbursementSummary.data.total,0);assert.equal(typeof reimbursementSummary.data.currency,'string');
 await call('/properties','POST',{name:'Invalid',location:'Here',type:'Villa',price:-1},400);
 await call('/leads','POST',{...fixtures.leads,unknown:true},400);
 await call('/leads','POST',fixtures.leads,401,'invalid-token');
 await call('/leads/507f1f77bcf86cd799439011','DELETE',undefined,403,agent.getSignedJwtToken());
 const roles=await call('/roles');
 for(const name of ['manager','senior-agent','agent','viewer','customer','staff'])assert.ok(roles.data.some(role=>role.name===name),'Missing built-in role '+name);
 assert.ok(roles.data.find(role=>role.name==='agent').permissions.includes('menu:leads'));
 assert.ok(roles.data.find(role=>role.name==='manager').permissions.includes('menu:reimbursements'));
 assert.ok(!roles.data.find(role=>role.name==='viewer').permissions.includes('menu:reimbursements'));
 const role=await call('/roles','POST',{name:'limited-agent',permissions:['leads:read','menu:leads']},201);
 await User.findByIdAndUpdate(agent.id,{role:'limited-agent'});
 await call('/leads','POST',fixtures.leads,403,agent.getSignedJwtToken());
 await call('/roles/'+role.data.id,'DELETE',undefined,409);
 await User.findByIdAndUpdate(agent.id,{role:'staff'});
 await call('/roles/'+role.data.id,'DELETE');

 const agentToken=agent.getSignedJwtToken();
 const streamController=new AbortController();
 const streamResponse=await fetch(base+'/chat/stream',{headers:{Authorization:'Bearer '+agentToken},signal:streamController.signal});assert.equal(streamResponse.status,200);checks++;
 const streamReader=streamResponse.body.getReader();const streamDecoder=new TextDecoder();
 let streamText=streamDecoder.decode((await streamReader.read()).value||new Uint8Array());assert.match(streamText,/event: connected/);
 const contacts=await call('/chat/contacts');assert.ok(contacts.data.some(contact=>contact.id===String(agent.id)));
 const internalMessage=await call('/chat/messages','POST',{recipientId:String(agent.id),text:'Live integration hello'},201);assert.equal(internalMessage.data.text,'Live integration hello');
 while(!streamText.includes('Live integration hello')){const streamed=await Promise.race([streamReader.read(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Chat stream timeout')),5000))]);streamText+=streamDecoder.decode(streamed.value||new Uint8Array());}
 assert.match(streamText,/event: message/);streamController.abort();
 const agentMessages=await call('/chat/messages/'+admin.id,'GET',undefined,200,agentToken);assert.equal(agentMessages.data.at(-1).text,'Live integration hello');
 await call('/chat/messages/'+admin.id+'/read','PUT',undefined,200,agentToken);
 await call('/chat/messages','POST',{recipientId:String(admin.id),text:'Staff reply'},201,agentToken);
 const viewerToken=viewer.getSignedJwtToken();
 await call('/chat/contacts','GET',undefined,403,viewerToken);
 await call('/chat/messages','POST',{recipientId:String(admin.id),text:'Not allowed'},403,viewerToken);
 const assistant=await call('/chat/assistant','POST',{text:'I want to schedule a property tour'},201,viewerToken);assert.equal(assistant.data.length,2);assert.equal(assistant.data[1].assistant,true);assert.match(assistant.data[1].text,/Appointments|Tour/i);
 const assistantHistory=await call('/chat/assistant','GET',undefined,200,viewerToken);assert.equal(assistantHistory.data.length,2);
 await call('/chat/assistant','POST',{text:'Not an assistant user'},403,token);

 const listingAgent=await call('/agents','POST',{name:'Notification Agent',email:'notify-agent@test.local',phone:'+15550002001',status:'Active'},201);
 const bookingProperty=await call('/properties','POST',{name:'Notification Test Home',location:'100 Delivery Lane',type:'Villa',price:750000,agentRef:listingAgent.data.id,agent:listingAgent.data.name,ownerName:'Test Property Owner',ownerEmail:'owner@test.local',ownerWhatsapp:'+15550002002'},201);
 await call('/appointments','POST',{title:'Missing property',client:'Spoofed visitor',when:'2030-03-15T10:00:00.000Z',requesterWhatsapp:'+15550002003'},400,viewerToken);
 const emailCount=sentEmails.length;const whatsappCount=sentWhatsapps.length;
 const booking=await call('/appointments','POST',{title:'Viewer visit',propertyRef:bookingProperty.data.id,client:'Spoofed visitor',requesterEmail:'spoofed@test.local',requesterWhatsapp:'+1 (555) 000-2003',when:'2030-03-15T10:00:00.000Z',notes:'Please confirm parking access.'},201,viewerToken);
 const deliveryLog=await call('/notification-deliveries');
 assert.equal(booking.data.client,viewer.name);assert.equal(booking.data.requesterEmail,viewer.email);assert.equal(booking.data.requesterWhatsapp,'+15550002003');assert.equal(booking.data.agentRef,listingAgent.data.id);assert.equal(booking.data.notificationStatus,'sent',JSON.stringify(deliveryLog.data));
 assert.equal(sentEmails.length-emailCount,2);assert.equal(sentWhatsapps.length-whatsappCount,2);assert.ok(sentEmails.slice(-2).every(message=>message.text.includes(viewer.email)&&message.text.includes('+15550002003')));
 assert.equal(deliveryLog.data.length,4);assert.equal(deliveryLog.summary.sent,4);assert.ok(deliveryLog.data.every(delivery=>delivery.status==='sent'&&delivery.attempts===1));
 await NotificationDelivery.findByIdAndUpdate(deliveryLog.data[0].id,{status:'failed',error:'Simulated provider outage'});
 const retried=await call('/notification-deliveries/'+deliveryLog.data[0].id+'/retry','POST');assert.equal(retried.data.status,'sent');assert.equal(retried.data.attempts,2);assert.equal(retried.data.error,'');
 await call('/notification-deliveries','GET',undefined,403,viewerToken);
 const adminNotifications=await call('/notifications');assert.ok(adminNotifications.data.some(notification=>notification.title==='New property visit request'&&notification.message.includes('Notification Test Home')));
 const viewerRole=roles.data.find(role=>role.name==='viewer');await call('/roles/'+viewerRole.id,'PUT',{permissions:viewerRole.permissions.filter(permission=>permission!=='appointments:create')});
 await call('/appointments','POST',{title:'Revoked visit',propertyRef:bookingProperty.data.id,client:viewer.name,requesterWhatsapp:'+15550002003',when:'2030-03-16T10:00:00.000Z'},403,viewerToken);
 await call('/roles/'+viewerRole.id,'PUT',{permissions:viewerRole.permissions});
 await call('/appointments/'+booking.data.id,'DELETE');await call('/properties/'+bookingProperty.data.id,'DELETE');await call('/agents/'+listingAgent.data.id,'DELETE');

 const imageForm=new FormData();
 imageForm.append('resource','properties');
 imageForm.append('images',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'property.png');
 const uploadResponse=await fetch(base+'/uploads/images',{method:'POST',headers:{Authorization:'Bearer '+token},body:imageForm});
 const uploaded=await uploadResponse.json();assert.equal(uploadResponse.status,201,JSON.stringify(uploaded));checks++;
 assert.match(uploaded.data[0].url,/^\/uploads\/properties\/.+\.png$/);
 uploadedFile=path.resolve(__dirname,'..',uploaded.data[0].url.replace(/^\//,''));
 const staticImage=await fetch(origin+uploaded.data[0].url);assert.equal(staticImage.status,200);checks++;
 const forbiddenImageForm=new FormData();forbiddenImageForm.append('resource','properties');forbiddenImageForm.append('images',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'property.png');
 const forbiddenUpload=await fetch(base+'/uploads/images',{method:'POST',headers:{Authorization:'Bearer '+agent.getSignedJwtToken()},body:forbiddenImageForm});assert.equal(forbiddenUpload.status,403);checks++;
 const invoice=await call('/invoices','POST',{client:'Tax test',issueDate:'2030-01-01',dueDate:'2030-01-10',items:[{description:'Service',quantity:2,unitPrice:100,tax:10}],amount:1},201);
 assert.equal(invoice.data.amount,220); assert.equal(invoice.data.items[0].tax,10);
 const payment=await call('/payments','POST',{reference:'LINK-1',client:'Tax test',amount:220,invoiceRef:invoice.data.id},201);
 await call('/invoices/'+invoice.data.id,'DELETE',undefined,409);await call('/payments/'+payment.data.id,'DELETE');await call('/invoices/'+invoice.data.id,'DELETE');
 await models.leads.insertMany(Array.from({length:125},(_,i)=>({...fixtures.leads,name:'Pagination '+i})));
 const page=await call('/leads?limit=100&page=2');assert.equal(page.data.length,25);assert.equal(page.total,125);
 await call('/workspace/settings','PUT',{companyName:'Integration Company',timezone:'Asia/Kolkata',currency:'INR'});
 assert.equal((await call('/workspace/settings')).data.companyName,'Integration Company');
 const report=await call('/workspace/reports?year=2030');assert.equal(report.data.months.length,12);assert.equal(report.data.currency,'INR');
 await call('/workspace/settings','GET',undefined,403,agent.getSignedJwtToken());
 await call('/workspace/settings','PUT',{companyName:'Unauthorized'},403,agent.getSignedJwtToken());
 await call('/auth/update-profile','PUT',{name:'Updated Admin',role:'staff'});assert.equal((await call('/auth/me')).data.role,'admin');
 await call('/auth/update-password','PUT',{currentPassword:'wrong',newPassword:'NewPassword123!'},401);
 await call('/auth/update-password','PUT',{currentPassword:'TestPassword123!',newPassword:'NewPassword123!'});
 for(const endpoint of ['summary','revenue-overview','activity-overview','property-status','property-categories','sales-pipeline','featured-listings','recent-activity'])await call('/dashboard/'+endpoint);
 const registered=await call('/auth/register','POST',{name:'Registered User',email:'register@test.local',password:'RegisterPassword123!',role:'admin'},201,'',{Origin:'https://socailsync.com'});
 assert.equal(registered.user.role,'customer');
 assert.match(lastEmail.text,/https:\/\/socailsync\.com\/verify-email\//);
 const customerAssistant=await call('/chat/assistant','POST',{text:'Help me find a rental'},201,registered.token);assert.equal(customerAssistant.data[1].assistant,true);assert.match(customerAssistant.data[1].text,/rent|lease|Properties/i);
 await call('/chat/contacts','GET',undefined,403,registered.token);
 const verification=lastEmail.text.match(/verify-email\/([a-f0-9]+)/)[1];
 await call('/auth/verify-email/'+verification,'GET',undefined,200,registered.token);
 await call('/auth/forgot-password','POST',{email:'register@test.local'},200,'',{Origin:'https://socailsync.com'});
 assert.match(lastEmail.text,/https:\/\/socailsync\.com\/reset-password\//);
 const resetToken=lastEmail.text.match(/reset-password\/([a-f0-9]+)/)[1];
 await call('/auth/reset-password/'+resetToken,'PUT',{password:'ResetPassword123!'},200,'');
 await call('/auth/reset-password/'+resetToken,'PUT',{password:'AnotherPassword123!'},400,'');
 await call('/auth/login','POST',{email:'register@test.local',password:'ResetPassword123!'},200,'');
 const custom=await call('/roles','POST',{name:'auditor',description:'Read only',permissions:['leads:read','dashboard:read','menu:leads','menu:dashboard']},201);
 const account=await call('/users','POST',{name:'Audit User',email:'auditor@test.local',password:'AuditorPassword123!',role:'auditor'},201);
 assert.equal(account.data.password,undefined);
 const accountLogin=await call('/auth/login','POST',{email:'auditor@test.local',password:'AuditorPassword123!'},200,'');
 const access=await call('/workspace/access','GET',undefined,200,accountLogin.token);assert.ok(access.data.permissions.includes('menu:leads'));assert.ok(!access.data.permissions.includes('menu:payments'));
 await call('/leads','GET',undefined,200,accountLogin.token);
 await call('/payments','GET',undefined,403,accountLogin.token);
 await call('/roles/'+custom.data.id,'PUT',{permissions:['leads:read']});
 const clearedAccess=await call('/workspace/access','GET',undefined,200,accountLogin.token);assert.ok(!clearedAccess.data.permissions.some(permission=>permission.startsWith('menu:')));
 await call('/roles/'+custom.data.id,'PUT',{permissions:['leads:read','menu:leads']});
 await call('/users/'+account.data.id,'PUT',{name:'Updated Audit User',password:''});
 await call('/users/'+account.data.id,'PUT',{active:false});
 await call('/auth/login','POST',{email:'auditor@test.local',password:'AuditorPassword123!'},403,'');
 await call('/users/'+admin.id,'PUT',{role:'agent'},409);
 await call('/users/'+admin.id,'DELETE',undefined,409);
 await call('/users/'+account.data.id,'DELETE');
 await call('/roles/'+custom.data.id,'DELETE');
 const audit=await call('/workspace/audit');assert.ok(audit.data.length>20);
 await User.findByIdAndUpdate(agent.id,{active:false});await call('/auth/me','GET',undefined,401,agent.getSignedJwtToken());
 console.log('PASS '+checks+' API assertions: CRUD, visit notifications, delivery status, live chat, assistant chat, uploads, validation, pagination, role menus, RBAC, references, reports, settings, profile, dashboard, audit.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{
 if(server)await new Promise(resolve=>server.close(resolve));
 if(uploadedFile && uploadedFile.startsWith(path.resolve(__dirname,'../uploads')+path.sep))await fs.unlink(uploadedFile).catch(()=>{});
 if(mongoose.connection.readyState===1 && mongoose.connection.name===dbName && dbName.startsWith('crm_integration_'))await mongoose.connection.dropDatabase();
 await mongoose.disconnect();
});

